import { StockInfo } from "./types";

export const STOCK_UNIVERSE: StockInfo[] = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", index: "NIFTY 50" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "IT", index: "NIFTY 50" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking", index: "NIFTY 50" },
  { symbol: "INFY.NS", name: "Infosys", sector: "IT", index: "NIFTY 50" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking", index: "NIFTY 50" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "FMCG", index: "NIFTY 50" },
  { symbol: "ITC.NS", name: "ITC Limited", sector: "FMCG", index: "NIFTY 50" },
  { symbol: "SBIN.NS", name: "State Bank of India", sector: "Banking", index: "NIFTY 50" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", index: "NIFTY 50" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking", index: "NIFTY 50" },
  { symbol: "LT.NS", name: "Larsen & Toubro", sector: "Capital Goods", index: "NIFTY 50" },
  { symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Banking", index: "NIFTY 50" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer Durables", index: "NIFTY 50" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki", sector: "Automobile", index: "NIFTY 50" },
  { symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer Durables", index: "NIFTY 50" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma", sector: "Pharma", index: "NIFTY 50" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Financial Services", index: "NIFTY 50" },
  { symbol: "WIPRO.NS", name: "Wipro", sector: "IT", index: "NIFTY 50" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "IT", index: "NIFTY 50" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Cement", index: "NIFTY 50" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", sector: "Automobile", index: "NIFTY 50" },
  { symbol: "NTPC.NS", name: "NTPC", sector: "Power", index: "NIFTY 50" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Metals", index: "NIFTY 50" },
  { symbol: "ONGC.NS", name: "ONGC", sector: "Energy", index: "NIFTY 50" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra", sector: "Automobile", index: "NIFTY 50" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Conglomerate", index: "NIFTY 50" },
  { symbol: "COALINDIA.NS", name: "Coal India", sector: "Mining", index: "NIFTY 50" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Financial Services", index: "NIFTY 50" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Metals", index: "NIFTY 50" },
  { symbol: "TECHM.NS", name: "Tech Mahindra", sector: "IT", index: "NIFTY 50" },
  { symbol: "NESTLEIND.NS", name: "Nestle India", sector: "FMCG", index: "NIFTY 50" },
  { symbol: "CIPLA.NS", name: "Cipla", sector: "Pharma", index: "NIFTY 50" },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's Labs", sector: "Pharma", index: "NIFTY 50" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Automobile", index: "NIFTY 50" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare", index: "NIFTY 50" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries", sector: "FMCG", index: "NIFTY 50" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Automobile", index: "NIFTY 50" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Automobile", index: "NIFTY 50" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "FMCG", index: "NIFTY 50" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries", sector: "Metals", index: "NIFTY 50" },
  { symbol: "BPCL.NS", name: "BPCL", sector: "Energy", index: "NIFTY 50" },
  { symbol: "HAVELLS.NS", name: "Havells India", sector: "Consumer Durables", index: "NIFTY NEXT 50" },
  { symbol: "DABUR.NS", name: "Dabur India", sector: "FMCG", index: "NIFTY NEXT 50" },
  { symbol: "SIEMENS.NS", name: "Siemens", sector: "Capital Goods", index: "NIFTY NEXT 50" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Banking", index: "NIFTY NEXT 50" },
  { symbol: "PNB.NS", name: "Punjab National Bank", sector: "Banking", index: "NIFTY NEXT 50" },
  { symbol: "DLF.NS", name: "DLF", sector: "Real Estate", index: "NIFTY NEXT 50" },
  { symbol: "ZOMATO.NS", name: "Zomato", sector: "Internet", index: "NIFTY NEXT 50" },
  { symbol: "IRCTC.NS", name: "IRCTC", sector: "Travel", index: "NIFTY NEXT 50" },
  { symbol: "TATAPOWER.NS", name: "Tata Power", sector: "Power", index: "NIFTY NEXT 50" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics", sector: "Defence", index: "NIFTY NEXT 50" },
  { symbol: "BEL.NS", name: "Bharat Electronics", sector: "Defence", index: "NIFTY NEXT 50" },
  { symbol: "VEDL.NS", name: "Vedanta", sector: "Metals", index: "NIFTY NEXT 50" },
  { symbol: "LUPIN.NS", name: "Lupin", sector: "Pharma", index: "NIFTY NEXT 50" },
];

export function searchStocks(query: string): StockInfo[] {
  const q = query.toLowerCase().trim();
  if (!q) return STOCK_UNIVERSE;
  return STOCK_UNIVERSE.filter(
    (s) => s.name.toLowerCase().includes(q) || s.symbol.toLowerCase().includes(q)
  );
}
