import { StockInfo } from "./types";

/* ─── 200 Global Stocks ─── */
export const STOCK_UNIVERSE: StockInfo[] = [
  // ── INDIAN STOCKS (NSE) ──
  { symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", exchange: "NSE" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "IT", exchange: "NSE" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "INFY.NS", name: "Infosys", sector: "IT", exchange: "NSE" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "FMCG", exchange: "NSE" },
  { symbol: "ITC.NS", name: "ITC Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "SBIN.NS", name: "State Bank of India", sector: "Banking", exchange: "NSE" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", exchange: "NSE" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "LT.NS", name: "Larsen & Toubro", sector: "Capital Goods", exchange: "NSE" },
  { symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer", exchange: "NSE" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki", sector: "Automobile", exchange: "NSE" },
  { symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer", exchange: "NSE" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma", sector: "Healthcare", exchange: "NSE" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Financial Services", exchange: "NSE" },
  { symbol: "WIPRO.NS", name: "Wipro", sector: "IT", exchange: "NSE" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "IT", exchange: "NSE" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Materials", exchange: "NSE" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", sector: "Automobile", exchange: "NSE" },
  { symbol: "NTPC.NS", name: "NTPC", sector: "Energy", exchange: "NSE" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Materials", exchange: "NSE" },
  { symbol: "ONGC.NS", name: "ONGC", sector: "Energy", exchange: "NSE" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra", sector: "Automobile", exchange: "NSE" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Conglomerate", exchange: "NSE" },
  { symbol: "COALINDIA.NS", name: "Coal India", sector: "Energy", exchange: "NSE" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Financial Services", exchange: "NSE" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Materials", exchange: "NSE" },
  { symbol: "TECHM.NS", name: "Tech Mahindra", sector: "IT", exchange: "NSE" },
  { symbol: "NESTLEIND.NS", name: "Nestle India", sector: "FMCG", exchange: "NSE" },
  { symbol: "CIPLA.NS", name: "Cipla", sector: "Healthcare", exchange: "NSE" },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's Labs", sector: "Healthcare", exchange: "NSE" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Automobile", exchange: "NSE" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare", exchange: "NSE" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries", sector: "FMCG", exchange: "NSE" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Automobile", exchange: "NSE" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Automobile", exchange: "NSE" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "FMCG", exchange: "NSE" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries", sector: "Materials", exchange: "NSE" },
  { symbol: "BPCL.NS", name: "BPCL", sector: "Energy", exchange: "NSE" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics", sector: "Defence", exchange: "NSE" },
  { symbol: "BEL.NS", name: "Bharat Electronics", sector: "Defence", exchange: "NSE" },
  { symbol: "TATAPOWER.NS", name: "Tata Power", sector: "Energy", exchange: "NSE" },
  { symbol: "DLF.NS", name: "DLF", sector: "Real Estate", exchange: "NSE" },
  { symbol: "ZOMATO.NS", name: "Zomato", sector: "Internet", exchange: "NSE" },
  { symbol: "IRCTC.NS", name: "IRCTC", sector: "Travel", exchange: "NSE" },
  { symbol: "PNB.NS", name: "Punjab National Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Banking", exchange: "NSE" },
  { symbol: "VEDL.NS", name: "Vedanta", sector: "Materials", exchange: "NSE" },

  // ── US STOCKS (NYSE/NASDAQ) ──
  { symbol: "AAPL", name: "Apple", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "GOOGL", name: "Alphabet (Google)", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "AMZN", name: "Amazon", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "META", name: "Meta Platforms", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "TSLA", name: "Tesla", sector: "Automobile", exchange: "NASDAQ" },
  { symbol: "BRK-B", name: "Berkshire Hathaway", sector: "Financial Services", exchange: "NYSE" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Banking", exchange: "NYSE" },
  { symbol: "V", name: "Visa", sector: "Financial Services", exchange: "NYSE" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer", exchange: "NYSE" },
  { symbol: "PG", name: "Procter & Gamble", sector: "FMCG", exchange: "NYSE" },
  { symbol: "MA", name: "Mastercard", sector: "Financial Services", exchange: "NYSE" },
  { symbol: "HD", name: "Home Depot", sector: "Consumer", exchange: "NYSE" },
  { symbol: "DIS", name: "Walt Disney", sector: "Media", exchange: "NYSE" },
  { symbol: "BAC", name: "Bank of America", sector: "Banking", exchange: "NYSE" },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energy", exchange: "NYSE" },
  { symbol: "PFE", name: "Pfizer", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "KO", name: "Coca-Cola", sector: "FMCG", exchange: "NYSE" },
  { symbol: "NFLX", name: "Netflix", sector: "Media", exchange: "NASDAQ" },
  { symbol: "CRM", name: "Salesforce", sector: "Technology", exchange: "NYSE" },
  { symbol: "AMD", name: "AMD", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "INTC", name: "Intel", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "CSCO", name: "Cisco", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "ADBE", name: "Adobe", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "ORCL", name: "Oracle", sector: "Technology", exchange: "NYSE" },
  { symbol: "NKE", name: "Nike", sector: "Consumer", exchange: "NYSE" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer", exchange: "NYSE" },
  { symbol: "COST", name: "Costco", sector: "Consumer", exchange: "NASDAQ" },
  { symbol: "CVX", name: "Chevron", sector: "Energy", exchange: "NYSE" },
  { symbol: "ABT", name: "Abbott Labs", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare", exchange: "NYSE" },
  { symbol: "LIN", name: "Linde", sector: "Materials", exchange: "NYSE" },
  { symbol: "T", name: "AT&T", sector: "Telecom", exchange: "NYSE" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Banking", exchange: "NYSE" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Banking", exchange: "NYSE" },
  { symbol: "PYPL", name: "PayPal", sector: "Financial Services", exchange: "NASDAQ" },
  { symbol: "SQ", name: "Block (Square)", sector: "Financial Services", exchange: "NYSE" },
  { symbol: "UBER", name: "Uber", sector: "Technology", exchange: "NYSE" },
  { symbol: "ABNB", name: "Airbnb", sector: "Travel", exchange: "NASDAQ" },
  { symbol: "SPOT", name: "Spotify", sector: "Media", exchange: "NYSE" },
  { symbol: "COIN", name: "Coinbase", sector: "Financial Services", exchange: "NASDAQ" },
  { symbol: "PLTR", name: "Palantir", sector: "Technology", exchange: "NYSE" },
  { symbol: "SNOW", name: "Snowflake", sector: "Technology", exchange: "NYSE" },
  { symbol: "NET", name: "Cloudflare", sector: "Technology", exchange: "NYSE" },
  { symbol: "SHOP", name: "Shopify", sector: "Technology", exchange: "NYSE" },
  { symbol: "ZS", name: "Zscaler", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "MU", name: "Micron", sector: "Technology", exchange: "NASDAQ" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technology", exchange: "NASDAQ" },

  // ── UK STOCKS (LSE) ──
  { symbol: "SHEL.L", name: "Shell", sector: "Energy", exchange: "LSE" },
  { symbol: "AZN.L", name: "AstraZeneca", sector: "Healthcare", exchange: "LSE" },
  { symbol: "HSBA.L", name: "HSBC Holdings", sector: "Banking", exchange: "LSE" },
  { symbol: "ULVR.L", name: "Unilever", sector: "FMCG", exchange: "LSE" },
  { symbol: "BP.L", name: "BP", sector: "Energy", exchange: "LSE" },
  { symbol: "GSK.L", name: "GSK", sector: "Healthcare", exchange: "LSE" },
  { symbol: "RIO.L", name: "Rio Tinto", sector: "Materials", exchange: "LSE" },
  { symbol: "LSEG.L", name: "LSEG", sector: "Financial Services", exchange: "LSE" },
  { symbol: "DGE.L", name: "Diageo", sector: "Consumer", exchange: "LSE" },
  { symbol: "BATS.L", name: "BAT", sector: "Consumer", exchange: "LSE" },
  { symbol: "LLOY.L", name: "Lloyds Banking", sector: "Banking", exchange: "LSE" },
  { symbol: "VOD.L", name: "Vodafone", sector: "Telecom", exchange: "LSE" },
  { symbol: "RKT.L", name: "Reckitt Benckiser", sector: "FMCG", exchange: "LSE" },
  { symbol: "BARC.L", name: "Barclays", sector: "Banking", exchange: "LSE" },
  { symbol: "BA.L", name: "BAE Systems", sector: "Defence", exchange: "LSE" },

  // ── EUROPE (XETRA) ──
  { symbol: "SAP.DE", name: "SAP", sector: "Technology", exchange: "XETRA" },
  { symbol: "SIE.DE", name: "Siemens", sector: "Capital Goods", exchange: "XETRA" },
  { symbol: "ALV.DE", name: "Allianz", sector: "Financial Services", exchange: "XETRA" },
  { symbol: "DTE.DE", name: "Deutsche Telekom", sector: "Telecom", exchange: "XETRA" },
  { symbol: "BAS.DE", name: "BASF", sector: "Materials", exchange: "XETRA" },
  { symbol: "BMW.DE", name: "BMW", sector: "Automobile", exchange: "XETRA" },
  { symbol: "MBG.DE", name: "Mercedes-Benz", sector: "Automobile", exchange: "XETRA" },
  { symbol: "VOW3.DE", name: "Volkswagen", sector: "Automobile", exchange: "XETRA" },
  { symbol: "ADS.DE", name: "Adidas", sector: "Consumer", exchange: "XETRA" },
  { symbol: "DPW.DE", name: "Deutsche Post", sector: "Logistics", exchange: "XETRA" },
  { symbol: "AIR.DE", name: "Airbus", sector: "Capital Goods", exchange: "XETRA" },
  { symbol: "MUV2.DE", name: "Munich Re", sector: "Financial Services", exchange: "XETRA" },
  { symbol: "RWE.DE", name: "RWE", sector: "Energy", exchange: "XETRA" },
  { symbol: "IFX.DE", name: "Infineon", sector: "Technology", exchange: "XETRA" },
  { symbol: "BEI.DE", name: "Beiersdorf", sector: "Consumer", exchange: "XETRA" },

  // ── ASIA (TSE + HKEX) ──
  { symbol: "7203.T", name: "Toyota", sector: "Automobile", exchange: "TSE" },
  { symbol: "6758.T", name: "Sony", sector: "Technology", exchange: "TSE" },
  { symbol: "6861.T", name: "Keyence", sector: "Technology", exchange: "TSE" },
  { symbol: "9984.T", name: "SoftBank", sector: "Technology", exchange: "TSE" },
  { symbol: "8306.T", name: "MUFG", sector: "Banking", exchange: "TSE" },
  { symbol: "6501.T", name: "Hitachi", sector: "Technology", exchange: "TSE" },
  { symbol: "7974.T", name: "Nintendo", sector: "Media", exchange: "TSE" },
  { symbol: "6902.T", name: "Denso", sector: "Automobile", exchange: "TSE" },
  { symbol: "7267.T", name: "Honda", sector: "Automobile", exchange: "TSE" },
  { symbol: "4502.T", name: "Takeda", sector: "Healthcare", exchange: "TSE" },
  { symbol: "0700.HK", name: "Tencent", sector: "Technology", exchange: "HKEX" },
  { symbol: "9988.HK", name: "Alibaba", sector: "Technology", exchange: "HKEX" },
  { symbol: "9618.HK", name: "JD.com", sector: "Technology", exchange: "HKEX" },
  { symbol: "1299.HK", name: "AIA Group", sector: "Financial Services", exchange: "HKEX" },
  { symbol: "0005.HK", name: "HSBC HK", sector: "Banking", exchange: "HKEX" },
  { symbol: "2318.HK", name: "Ping An", sector: "Financial Services", exchange: "HKEX" },
  { symbol: "0941.HK", name: "China Mobile", sector: "Telecom", exchange: "HKEX" },
  { symbol: "3690.HK", name: "Meituan", sector: "Technology", exchange: "HKEX" },
  { symbol: "1810.HK", name: "Xiaomi", sector: "Technology", exchange: "HKEX" },
  { symbol: "2020.HK", name: "ANTA Sports", sector: "Consumer", exchange: "HKEX" },

  // ── ETFs ──
  { symbol: "SPY", name: "S&P 500 ETF", sector: "Index ETF", exchange: "NYSE" },
  { symbol: "QQQ", name: "NASDAQ 100 ETF", sector: "Index ETF", exchange: "NASDAQ" },
  { symbol: "DIA", name: "Dow Jones ETF", sector: "Index ETF", exchange: "NYSE" },
  { symbol: "IWM", name: "Russell 2000 ETF", sector: "Index ETF", exchange: "NYSE" },
  { symbol: "VTI", name: "Total US Market ETF", sector: "Index ETF", exchange: "NYSE" },
  { symbol: "EEM", name: "Emerging Markets ETF", sector: "Index ETF", exchange: "NYSE" },
  { symbol: "GLD", name: "Gold ETF", sector: "Commodity ETF", exchange: "NYSE" },
  { symbol: "TLT", name: "20+ Year Treasury ETF", sector: "Bond ETF", exchange: "NASDAQ" },
  { symbol: "XLF", name: "Financial Sector ETF", sector: "Sector ETF", exchange: "NYSE" },
  { symbol: "XLK", name: "Technology Sector ETF", sector: "Sector ETF", exchange: "NYSE" },
];

export function searchStocks(query: string): StockInfo[] {
  const q = query.toLowerCase().trim();
  if (!q) return STOCK_UNIVERSE;
  return STOCK_UNIVERSE.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.symbol.toLowerCase().includes(q) ||
      s.sector.toLowerCase().includes(q) ||
      s.exchange.toLowerCase().includes(q)
  );
}

export function getExchanges(): string[] {
  return [...new Set(STOCK_UNIVERSE.map((s) => s.exchange))];
}

export function getSectors(): string[] {
  return [...new Set(STOCK_UNIVERSE.map((s) => s.sector))].sort();
}
